### ISSUE TITLE
Keyboards "pair" but don't actually work

### ISSUE THREAD

**Issue by lyricalpolymath** [DDRBoxman/Bluetooth-Manager-for-Glass#3]
Any idea why this happens? I managed to perfectly pair the device but the strokes don't work. It's not the Keyboard per se as I've successfully connected it to my Nexus5 (which of course has KitKat on).
 I've heard that there are people who managed to connect their Apple keyboard. 
Could it be because of XE12? any other idea?

besides this it's an excellent piece of software. works better than many other glasswares

**Comment by DDRBoxman** [comment]
I've actually had the same problem on my device. I haven't been able to get a keyboard to pair since XE11 with this app or others.

**Comment by lyricalpolymath** [comment]
ok. thanks for pointing it out. maybe a note about this on the readme file and the companion website might be useful :) thanks for trying it out anyways.
And a note: my keyboard DOES pair...I see it in the paired devices... but then it doesn't act upon the glass: if I press the arrows or Esc button it doesn't do anything like it did on my nexus

**Comment by DDRBoxman** [comment]
Merging into #6
