### ISSUE TITLE
Xe18 Update and Confirmation

### ISSUE THREAD

**Issue by RichardTrainer** [DDRBoxman/Bluetooth-Manager-for-Glass#8]
Hi I down loaded BM a couple of weeks ago and everything was fine.  Paired no problem.  Then Glass updated itself and not I cant pair, discover or anything.  It now has XE18.1 on it.  Any help on how to get it working again would be great.  

Also is it possible to surpress the "Do you want to Pair? " confirmation that pops up?  Obviously without a keyboard one is a bit stumped how to answer.   Apparently there is a bluetooth setting that will surpress this.  

Best Wishes 
Richard

**Comment by DDRBoxman** [comment]
Merging into #6
